# rose-pine-moon
[colors]
foreground = "#e5e1f7"
background = "#000000"
cursor_bg = "#e5e1f7"
cursor_border = "#000000"
cursor_fg = "#e5e1f7"
selection_bg = "#e5e1f7"
selection_fg = "#2b2c2e"

ansi = ["#393552", "#eb6f92", "#3e8fb0", "#f6c177", "#9ccfd8", "#c4a7e7", "#ebbcba", "#e0def4"]
brights = ["817c9c", "#eb6f92", "#3e8fb0", "#f6c177", "#9ccfd8", "#c4a7e7", "#ebbcba", "#e0def4"]