#!/bin/bash
# Set GTK Themes, Icons, Cursor and Fonts

THEME='Materia-dark'
ICONS='Tela-circle-black-dark'
FONT='CascaydiaCove NF 11'
CURSOR='Graphite-dark-cursors'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes() {
    ${SCHEMA} gtk-theme "$THEME"
    ${SCHEMA} icon-theme "$ICONS"
    ${SCHEMA} cursor-theme "$CURSOR"
    ${SCHEMA} font-name "$FONT"
}

apply_themes
