#!/bin/bash
#  (                   (                (     
#  )\ )  *   )   (     )\ )  *   )      )\ )  
# (()/(` )  /(   )\   (()/(` )  /(   ( (()/(  
#  /(_))( )(_)|(((_)(  /(_))( )(_))  )\ /(_)) 
# (_)) (_(_()) )\ _ )\(_)) (_(_())_ ((_|_))   
# / __||_   _| (_)_\(_) _ \|_   _| | | | _ \  
# \__ \  | |    / _ \ |   /  | | | |_| |  _/  
# |___/  |_|   /_/ \_\|_|_\  |_|  \___/|_|    
                                          

SCRIPTSDIR=$HOME/.scripts

# Apply Themes
${SCRIPTSDIR}/gtkthemes &

# Start Notifications
${SCRIPTSDIR}/notifications &

# Establish Xauthority
${SCRIPTSDIR}/xauthority &

# Delete Looking-Glass File
sudo rm /dev/shm/looking-glass
