#!/bin/bash

SCRIPTSDIR=$HOME/.scripts

# Kill process if already running
_ps=(waybar mako dunst)
for _prs in "${_ps[@]}"; do
    if [[ $(pidof ${_prs}) ]]; then
        killall -9 ${_prs}
    fi
done

# Start Waybar
${SCRIPTSDIR}/statusbar &

# Apply Themes
${SCRIPTSDIR}/gtkthemes &

# Start Notifications
${SCRIPTSDIR}/notifications &

# Establish Xauthority
${SCRIPTSDIR}/xauthority &
